### ISSUE TITLE
Error: Bad module 'main'

### ISSUE THREAD

**Issue by AlexanderLesnyakov** [rm-yakovenko/nomeroff-net-docker#39]
While running 'docker-compose up' there is an issue happen:
![image](https://user-images.githubusercontent.com/11361340/146038666-a79056b8-9f5c-4351-9345-2444a6bd5bec.png)
and then:
![image](https://user-images.githubusercontent.com/11361340/146038742-0bed5faa-31af-4361-8e3d-3163c4f8d7ea.png)

And the app constantly restarts.

I would be grateful for help with solving this issue.

P.S. Thanks for your efforts to make it easy to build and run this project.

**Comment by rm-yakovenko** [comment]
Thank you for the report!

I'll look into it ASAP.

**Comment by rm-yakovenko** [comment]
@AlexanderLesnyakov , I was able to reproduce the issue with the previous version of **nomeroff-net-docker**.

Could you try to fetch the latest version and try to reproduce the issue?

Unfortunately, it's impossible to maintain all previous versions.

Looking forward to your feedback.

**Comment by AlexanderLesnyakov** [comment]
@rm-yakovenko, yep, seems like I tried to run it a couple of weeks ago, and was faced with the issue. 
Now just cleaned everything up and it works like a charm.

Sorry for misleading you.

Thanks!
